#!/bin/bash


export FILENAME=.ubunut.base.qcow2
export FILEMD5=ea7f44d2aecb9f9fad69b9c896639c7d
[[  -f $PWD/$FILENAME ]] ||  exit 1
export result=`md5sum $PWD/$FILENAME | cut -d" " -f1` 
[[ "$FILEMD5" != "$result" ]]   &&  exit 1

echo "ok"
exit 0